### ISSUE TITLE
Number of tasks

### ISSUE THREAD

**Issue by BMD91** [aPissarek/webapp22-pissarek#6]
Dear Ms. Pissarek,
Due to the limit of our company and request from our directory and our chairman, I think we should shorten your requirement to 10 tasks instead of 12 tasks. By doing that, I as a developer recommend, at the part about "Classes", we can drop "Creating new class" and "Deleting an existing class". Because your school has a fixed number of classes, I think we don't need to use these functions.

**Comment by aPissarek** [comment]
In my app description, the number of classes is not fixed. But for simplicity's sake, we can make this assumption. in that case we will have classes a, b and c. 
That means for first grade level, we will have classes 1a, 1b and 1c. For second grade level 2a, 2b and 2c, and so on (up to 4).
