### ISSUE TITLE
Teacher's name

### ISSUE THREAD

**Issue by BMD91** [aPissarek/webapp22-pissarek#8]
Can I combine "First name" and "Last name" of Teacher in just one field "Name"? I think it could be better to have an overview of the retrieval data.

**Comment by aPissarek** [comment]
If you really want to, you can do it but I would recommend against it since we expect the first name to be immutable and the last name to be updatable in case of marriage or divorce.

**Comment by BMD91** [comment]
I would make it as just "name", because you can change it later in the app.
